export default {
    activeName: 'first',
    students: [],
    teachers: [],
    courses: [],
    comments: [],
    evaluations: [],
    notices: [],
    chapter: [],
    allCourses: [],
    FileData: [],
    discussion: [],
    subDiscussion: [],
    singleCourse: [],
    LivingNotices: [],
    allLivingCourses: [],
    courseProgress: [],
    LastWatchedTime: [],
}